FROM alpine:edge

LABEL "MAINTAINER"="icaoberg", "luism"
LABEL "EMAIL"="icaoberg@psc.edu", "luism@psc.edu"
LABEL "SUPPORT"="help@psc.edu"
LABEL "REPOSITORY"="http://github.com/pscedu/singularity-hyperfine"
LABEL "COPYRIGHT"="Copyright © 2021-2025 Pittsburgh Supercomputing Center. All Rights Reserved."
LABEL "VERSION"="1.19.0"

RUN apk update && apk add hyperfine
